DjangoUploadModelForm/DjangoUploadModelForm/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from tutorials import views

urlpatterns = [
    path('tutorials/upload/', views.uploadTutorial, name='upload_tutorial'),
    path('tutorials/', views.tutorialList, name='tutorial_list'),
    path('tutorials/<int:pk>', views.deleteTutorial, name='tutorial'),
    path('update/<int:pk>',views.updateTutorial,name='update_tutorial'),
    path('edit/<int:pk>',views.editTutorial,name='edit')
]

if settings.DEBUG:  # remember to set 'DEBUG = True' in settings.py
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoUploadModelForm/tutorials/models.py
from django.db import models


select = (
    ('1','1'),
    ('2','2'),
)

class Tutorial(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    feature_image = models.ImageField(upload_to='tutorial/images/')
    attachment = models.FileField(upload_to='tutorial/attachments/')
    select = models.CharField(max_length=10,choices=select,default='1')

DjangoUploadModelForm/tutorials/forms.py
from django import forms

from .models import Tutorial


class TutorialForm(forms.ModelForm):

    class Meta:
        model = Tutorial
        fields = ['title', 'category', 'feature_image', 'attachment','select']

DjangoUploadModelForm/tutorials/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse
from .forms import TutorialForm
from .models import Tutorial


def tutorialList(request):
    tutorials = Tutorial.objects.all()
    return render(request, 'tutorial/list.html', { 'tutorials' : tutorials})


def uploadTutorial(request):
    if request.method == 'POST':  
        form = TutorialForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('tutorial_list')
    else:
        form = TutorialForm()
    return render(request, 'tutorial/upload.html', {'form' : form})

def editTutorial(request,pk):
    tutorials = Tutorial.objects.get(id=pk)
    return render(request,'tutorial/update.html',{'t':tutorials})


def updateTutorial(request,pk):
    tutorials = Tutorial.objects.get(id=pk)
    form = TutorialForm(request.POST,request.FILES,instance=Tutorial)
    if form.is_valid():
        #form.feature_image = form.changed_data['feature_image']
        #form.attachment = form.changed_data['attachment']

        form.save()
        return HttpResponse('done')
    else:
        return HttpResponse('not done')
    #return render(request,'tutorial/update.html',{'t':tutorials})


def deleteTutorial(request, pk):
    if request.method == 'POST':
        tutorial = Tutorial.objects.get(pk=pk)
        tutorial.delete()
    return redirect('tutorial_list')

DjangoUploadModelForm/templates/tutorial/list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/tutorial.css' %}">

<h2>grokonez Tutorials</h2>

<a href="{% url 'upload_tutorial' %}">Upload Tutorial</a>

{% if tutorials %}
<table style="margin: 20px;">
	<thead>
		<tr>
			<th>Feature Image</th>
			<th>Title</th>
			<th>Category</th>
			<th>Attachment</th>
			<th>Select</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for tutorial in tutorials %}
		<tr>
			<td><img src="{{ tutorial.feature_image.url }}" width="150px"></td>
			<td>{{ tutorial.title }}</td>
			<td>{{ tutorial.category }}</td>
			<td><a href="{{ tutorial.attachment.url }}" target="_blank">Download</a></td>
			<td>{{ tutorial.select }}</td>
			<td>
				<a href="/edit/{{ tutorial.pk }}">update</a>

				<form method="post" action="{% url 'tutorial' tutorial.pk %}">
					{% csrf_token %}
					<button type="submit">Delete</button>
				</form>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

DjangoUploadModelForm/templates/tutorial/update.html
<h2>update</h2>

<form method="POST" action="/tutorials/">
	{% csrf_token %}
	<div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Name:</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_title" required maxlength="20" value="{{ t.title }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">category:</label>
    <div class="col-sm-4">
        <input type="text" name="category" id="id_category" required maxlength="100" value="{{ t.category }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">feature_image:</label>
    <div class="col-sm-4">
        <input type="file" accept="/image" name="feature_image" id="id_feature_image" value="{{ t.feature_image }}"/>
    </div>
  </div>
    <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">attachment:</label>
    <div class="col-sm-4">
        <input type="file" accept="/attachment" name="attachment" id="id_attachment" value="{{ t.attachment }}" />
    </div>
  </div>
        <div class="form-group row">
    <label for="" class="col-sm-2 col-form-label">Select:</label>
    <div class="col-sm-4">
    <select name = 'select' id="t_select" >
        <option value="1" selected>1</option>
        <option value="2">2</option>
    </select>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>

DjangoUploadModelForm/templates/tutorial/upload.html
<h2>grokonez upload Tutorial</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Upload</button>
</form>